# Generated by Django 5.0.6 on 2024-05-29 22:41

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32)),
                ('last_modified', models.DateField(auto_now=True, verbose_name='Last Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(auto_now_add=True, verbose_name='Snapshot Date')),
                ('listening_time', models.IntegerField(default=0)),
                ('top_genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), null=True, size=3)),
                ('song_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), null=True, size=5)),
                ('artist_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), null=True, size=5)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.profile')),
            ],
        ),
    ]
