# Generated by Django 5.0.6 on 2024-05-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_remove_topsongs_usersnapshot_usersnapshot_artistids_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSnapshot',
            new_name='Snapshot',
        ),
    ]
