# Generated by Django 5.0.6 on 2024-06-04 08:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_profile_snapshot_cached_alter_profile_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='profile_picture',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='artist_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=5),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='song_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=5),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='top_genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=3),
        ),
    ]
