# Generated by Django 5.0.6 on 2024-06-04 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_snapshot_profile_picture_snapshot_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snapshot',
            old_name='profile_picture',
            new_name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='snapshot_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_cached',
            field=models.DateTimeField(default=datetime.date(1, 1, 1), verbose_name='Last Cached'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_saved',
            field=models.DateTimeField(default=datetime.date(1, 1, 1), verbose_name='Last Saved'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='date',
            field=models.DateField(default=datetime.date(1, 1, 1), verbose_name='Date Saved'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='username',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
