# Generated by Django 5.0.6 on 2024-06-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0005_alter_snapshot_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_cached',
        ),
    ]
