# Generated by Django 5.0.6 on 2024-05-29 10:41

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshotDate', models.DateField(auto_now_add=True)),
                ('listeningTime', models.IntegerField(default=0)),
                ('topGenres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.user')),
            ],
        ),
        migrations.CreateModel(
            name='topSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songIDs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=5)),
                ('userSnapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userdata.usersnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='topArtists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistIDs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=5)),
                ('userSnapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userdata.usersnapshot')),
            ],
        ),
    ]
