# Generated by Django 5.0.6 on 2024-05-29 10:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topsongs',
            name='userSnapshot',
        ),
        migrations.AddField(
            model_name='usersnapshot',
            name='artistIDs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), null=True, size=5),
        ),
        migrations.AddField(
            model_name='usersnapshot',
            name='songIDs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), null=True, size=5),
        ),
        migrations.AlterField(
            model_name='usersnapshot',
            name='topGenres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), null=True, size=3),
        ),
        migrations.DeleteModel(
            name='topArtists',
        ),
        migrations.DeleteModel(
            name='topSongs',
        ),
    ]
